### ISSUE TITLE
Visualization: conformize file names

### ISSUE THREAD

**Issue by richelbilderbeek** [programming-formalisms/programming_formalisms_project_summer_2024#33]
Currently, the class `Visualization` is stored in the file `class_visualisation.py`. 

As far as I know, This is a nonstandard naming. AFAIK, Standard naming uses underscores and lower case without mentioning `class_`. If you feel the need, you may disagree with to force me to look into the literature :-)

Please rename the files in `src` and `test` to have lower case and underscores :+1:

**Comment by richelbilderbeek** [comment]
Indeed, the test file was not in tests yet. Silly me :-)

**Comment by richelbilderbeek** [comment]
Well done!

**Comment by AitorAldama** [comment]
src file is not updated

**Comment by monikaBrandt** [comment]
Nothing more to do
