### ISSUE TITLE
Visualisation: Create Visualisation

### ISSUE THREAD

**Issue by richelbilderbeek** [programming-formalisms/programming_formalisms_project_summer_2024#37]
In the class design document of this project (`design/README.md`), the class in the title is mentioned. Create it!

# Procedure

 * [x] Create a file for the class implementation
   with name `src/bacsim/[class_name].py`,
   e.g. `src/bacsim/simulation_parameters.py`

Already done! Well done!

 * [x] Create a file for the class tests,
   with name `tests/test-[class_name].py`,
   e.g. `tests/test-simulation_parameters.py`
 * [x] Create a minimal class implementation,
   for example:

```python
"""Simulation parameters."""

class SimulationParameters:

    """SimulationParameters holds the simulation's parameters."""
```

 * [x] Create a minimal class test,
   for example:

```python
"""Tests all function in src.bacsim.simulation_parameters."""
import unittest

from src.bacsim.simulation_parameters import (
    SimulationParameters,
)


class TestSimulationParameters(unittest.TestCase):

    """Class to test the code in src.bacsim.simulation_parameters."""

    def test_can_create_params(self):
        """#14: Can construct a SimulationParameters."""
        SimulationParameters()
```

The test is that it works, not that it does anything useful.

Use [the workflow that fits you best](https://github.com/programming-formalisms/programming_formalisms_example_project/tree/main/workflow#github-workflows), 
ideally use a topic branch for this issue 
and merge to develop using a PR with code review.

**Comment by monikaBrandt** [comment]
@richelbilderbeek Are you sure you want us to name the files to test-<name>.py and not test_<name>.py?
